"""initial_schema

Revision ID: 62069b40a737
Revises: 
Create Date: 2026-04-21 12:57:13.516053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62069b40a737'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zl_companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('sub_industry', sa.String(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('employee_range', sa.String(), nullable=True),
    sa.Column('revenue', sa.String(), nullable=True),
    sa.Column('funding_stage', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('is_hiring', sa.Boolean(), nullable=True),
    sa.Column('job_posting_count', sa.Integer(), nullable=True),
    sa.Column('last_funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_the_news', sa.Boolean(), nullable=True),
    sa.Column('news_summary', sa.Text(), nullable=True),
    sa.Column('google_maps_id', sa.String(), nullable=True),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('google_reviews', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('GOOGLE_MAPS', 'GOOGLE_SEARCH', 'WEBSITE', 'LINKEDIN', 'JOB_BOARD', 'GOVERNMENT', 'NEWS', 'LANDING_PAGE', 'BROADCAST', 'REFERRAL', 'MANUAL', 'INTERNAL_DB', name='leadsource'), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_maps_id')
    )
    op.create_index(op.f('ix_zl_companies_city'), 'zl_companies', ['city'], unique=False)
    op.create_index(op.f('ix_zl_companies_country'), 'zl_companies', ['country'], unique=False)
    op.create_index('ix_zl_companies_country_industry', 'zl_companies', ['country', 'industry'], unique=False)
    op.create_index(op.f('ix_zl_companies_domain'), 'zl_companies', ['domain'], unique=False)
    op.create_index(op.f('ix_zl_companies_industry'), 'zl_companies', ['industry'], unique=False)
    op.create_index('ix_zl_companies_industry_city', 'zl_companies', ['industry', 'city'], unique=False)
    op.create_index(op.f('ix_zl_companies_name'), 'zl_companies', ['name'], unique=False)
    op.create_table('zl_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'STARTER', 'GROWTH', 'PRO', 'AGENCY', name='plantier'), nullable=False),
    sa.Column('leads_used_this_month', sa.Integer(), nullable=False),
    sa.Column('leads_limit', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('billing_status', sa.String(), nullable=True),
    sa.Column('zims_linked', sa.Boolean(), nullable=True),
    sa.Column('zims_agency_id', sa.String(), nullable=True),
    sa.Column('zims_api_key', sa.String(), nullable=True),
    sa.Column('digest_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_outreach_enabled', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_zl_users_email'), 'zl_users', ['email'], unique=True)
    op.create_table('zl_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('campaign_type', sa.Enum('PROMOTION', 'FOLLOW_UP', 'FESTIVE', 'RE_ENGAGE', 'REFERRAL', 'EVENT', 'RENEWAL', name='campaigntype'), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'SMS', 'LINKEDIN', name='outreachchannel'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('delivered_count', sa.Integer(), nullable=True),
    sa.Column('replied_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_campaigns_user_id'), 'zl_campaigns', ['user_id'], unique=False)
    op.create_table('zl_exports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('lead_count', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('sheets_url', sa.String(), nullable=True),
    sa.Column('filters_used', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_exports_user_id'), 'zl_exports', ['user_id'], unique=False)
    op.create_table('zl_icps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=True),
    sa.Column('job_titles', sa.JSON(), nullable=True),
    sa.Column('seniority_levels', sa.JSON(), nullable=True),
    sa.Column('company_sizes', sa.JSON(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('intent_signals', sa.JSON(), nullable=True),
    sa.Column('search_queries', sa.JSON(), nullable=True),
    sa.Column('total_leads_generated', sa.Integer(), nullable=True),
    sa.Column('total_converted', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zl_icps_user_active', 'zl_icps', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_zl_icps_user_id'), 'zl_icps', ['user_id'], unique=False)
    op.create_table('zl_landing_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('subheadline', sa.String(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('whatsapp_num', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('brand_color', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('leads_captured', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_landing_pages_slug'), 'zl_landing_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_zl_landing_pages_user_id'), 'zl_landing_pages', ['user_id'], unique=False)
    op.create_table('zl_notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_notifications_is_read'), 'zl_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_zl_notifications_user_id'), 'zl_notifications', ['user_id'], unique=False)
    op.create_index('ix_zl_notifications_user_unread', 'zl_notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('zl_people',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_confidence', sa.Float(), nullable=True),
    sa.Column('email_source', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('linkedin_id', sa.String(), nullable=True),
    sa.Column('linkedin_activity', sa.Text(), nullable=True),
    sa.Column('recent_posts', sa.JSON(), nullable=True),
    sa.Column('job_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_title', sa.String(), nullable=True),
    sa.Column('previous_company', sa.String(), nullable=True),
    sa.Column('data_source', sa.Enum('GOOGLE_MAPS', 'GOOGLE_SEARCH', 'WEBSITE', 'LINKEDIN', 'JOB_BOARD', 'GOVERNMENT', 'NEWS', 'LANDING_PAGE', 'BROADCAST', 'REFERRAL', 'MANUAL', 'INTERNAL_DB', name='leadsource'), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['zl_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_people_company_id'), 'zl_people', ['company_id'], unique=False)
    op.create_index(op.f('ix_zl_people_email'), 'zl_people', ['email'], unique=False)
    op.create_index(op.f('ix_zl_people_full_name'), 'zl_people', ['full_name'], unique=False)
    op.create_index(op.f('ix_zl_people_job_title'), 'zl_people', ['job_title'], unique=False)
    op.create_table('zl_suppression_list',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_suppression_list_user_id'), 'zl_suppression_list', ['user_id'], unique=False)
    op.create_index(op.f('ix_zl_suppression_list_value'), 'zl_suppression_list', ['value'], unique=False)
    op.create_index('ix_zl_suppression_user_value', 'zl_suppression_list', ['user_id', 'value'], unique=False)
    op.create_table('zl_team_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_team_members_user_id'), 'zl_team_members', ['user_id'], unique=False)
    op.create_table('zl_content_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'FACEBOOK', 'LINKEDIN', 'WHATSAPP', 'YOUTUBE', 'TIKTOK', name='contentplatform'), nullable=True),
    sa.Column('content_type', sa.Enum('POST', 'CAPTION', 'REEL_SCRIPT', 'STORY', 'AD_COPY', 'BROADCAST', name='contenttype'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('icp_id', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('leads_from', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['icp_id'], ['zl_icps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_content_items_user_id'), 'zl_content_items', ['user_id'], unique=False)
    op.create_table('zl_leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('icp_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('lead_tier', sa.Enum('HOT', 'WARM', 'POTENTIAL', 'COLD', name='leadtier'), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('intent_signals', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'REPLIED', 'MEETING', 'CLOSED', 'LOST', 'SUPPRESSED', name='leadstatus'), nullable=True),
    sa.Column('source', sa.Enum('GOOGLE_MAPS', 'GOOGLE_SEARCH', 'WEBSITE', 'LINKEDIN', 'JOB_BOARD', 'GOVERNMENT', 'NEWS', 'LANDING_PAGE', 'BROADCAST', 'REFERRAL', 'MANUAL', 'INTERNAL_DB', name='leadsource'), nullable=True),
    sa.Column('ai_whatsapp_msg', sa.Text(), nullable=True),
    sa.Column('ai_email_subject', sa.String(), nullable=True),
    sa.Column('ai_email_body', sa.Text(), nullable=True),
    sa.Column('ai_linkedin_note', sa.Text(), nullable=True),
    sa.Column('ai_sms_message', sa.Text(), nullable=True),
    sa.Column('outreach_sent', sa.Boolean(), nullable=True),
    sa.Column('last_outreach_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outreach_channel', sa.Enum('EMAIL', 'WHATSAPP', 'SMS', 'LINKEDIN', name='outreachchannel'), nullable=True),
    sa.Column('linkedin_status', sa.String(), nullable=True),
    sa.Column('email_opened', sa.Boolean(), nullable=True),
    sa.Column('email_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('link_clicked', sa.Boolean(), nullable=True),
    sa.Column('link_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('page_visited', sa.Boolean(), nullable=True),
    sa.Column('page_visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zims_lead_id', sa.String(), nullable=True),
    sa.Column('zims_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['zl_team_members.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['zl_companies.id'], ),
    sa.ForeignKeyConstraint(['icp_id'], ['zl_icps.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['zl_people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_leads_company_id'), 'zl_leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_zl_leads_icp_id'), 'zl_leads', ['icp_id'], unique=False)
    op.create_index(op.f('ix_zl_leads_lead_score'), 'zl_leads', ['lead_score'], unique=False)
    op.create_index(op.f('ix_zl_leads_lead_tier'), 'zl_leads', ['lead_tier'], unique=False)
    op.create_index(op.f('ix_zl_leads_person_id'), 'zl_leads', ['person_id'], unique=False)
    op.create_index(op.f('ix_zl_leads_status'), 'zl_leads', ['status'], unique=False)
    op.create_index(op.f('ix_zl_leads_user_id'), 'zl_leads', ['user_id'], unique=False)
    op.create_index('ix_zl_leads_user_score', 'zl_leads', ['user_id', 'lead_score'], unique=False)
    op.create_index('ix_zl_leads_user_status', 'zl_leads', ['user_id', 'status'], unique=False)
    op.create_index('ix_zl_leads_user_tier', 'zl_leads', ['user_id', 'lead_tier'], unique=False)
    op.create_table('zl_campaign_contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'OPENED', 'REPLIED', 'BOUNCED', 'FAILED', name='outreachstatus'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('became_lead', sa.Boolean(), nullable=True),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['zl_campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['zl_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_campaign_contacts_campaign_id'), 'zl_campaign_contacts', ['campaign_id'], unique=False)
    op.create_table('zl_lead_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['zl_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_lead_history_lead_id'), 'zl_lead_history', ['lead_id'], unique=False)
    op.create_table('zl_scoring_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('original_score', sa.Integer(), nullable=True),
    sa.Column('original_breakdown', sa.JSON(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('conversion_value', sa.Float(), nullable=True),
    sa.Column('feedback_signal', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['zl_leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['zl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zl_scoring_feedback_lead_id'), 'zl_scoring_feedback', ['lead_id'], unique=False)
    op.create_index(op.f('ix_zl_scoring_feedback_user_id'), 'zl_scoring_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zl_scoring_feedback_user_id'), table_name='zl_scoring_feedback')
    op.drop_index(op.f('ix_zl_scoring_feedback_lead_id'), table_name='zl_scoring_feedback')
    op.drop_table('zl_scoring_feedback')
    op.drop_index(op.f('ix_zl_lead_history_lead_id'), table_name='zl_lead_history')
    op.drop_table('zl_lead_history')
    op.drop_index(op.f('ix_zl_campaign_contacts_campaign_id'), table_name='zl_campaign_contacts')
    op.drop_table('zl_campaign_contacts')
    op.drop_index('ix_zl_leads_user_tier', table_name='zl_leads')
    op.drop_index('ix_zl_leads_user_status', table_name='zl_leads')
    op.drop_index('ix_zl_leads_user_score', table_name='zl_leads')
    op.drop_index(op.f('ix_zl_leads_user_id'), table_name='zl_leads')
    op.drop_index(op.f('ix_zl_leads_status'), table_name='zl_leads')
    op.drop_index(op.f('ix_zl_leads_person_id'), table_name='zl_leads')
    op.drop_index(op.f('ix_zl_leads_lead_tier'), table_name='zl_leads')
    op.drop_index(op.f('ix_zl_leads_lead_score'), table_name='zl_leads')
    op.drop_index(op.f('ix_zl_leads_icp_id'), table_name='zl_leads')
    op.drop_index(op.f('ix_zl_leads_company_id'), table_name='zl_leads')
    op.drop_table('zl_leads')
    op.drop_index(op.f('ix_zl_content_items_user_id'), table_name='zl_content_items')
    op.drop_table('zl_content_items')
    op.drop_index(op.f('ix_zl_team_members_user_id'), table_name='zl_team_members')
    op.drop_table('zl_team_members')
    op.drop_index('ix_zl_suppression_user_value', table_name='zl_suppression_list')
    op.drop_index(op.f('ix_zl_suppression_list_value'), table_name='zl_suppression_list')
    op.drop_index(op.f('ix_zl_suppression_list_user_id'), table_name='zl_suppression_list')
    op.drop_table('zl_suppression_list')
    op.drop_index(op.f('ix_zl_people_job_title'), table_name='zl_people')
    op.drop_index(op.f('ix_zl_people_full_name'), table_name='zl_people')
    op.drop_index(op.f('ix_zl_people_email'), table_name='zl_people')
    op.drop_index(op.f('ix_zl_people_company_id'), table_name='zl_people')
    op.drop_table('zl_people')
    op.drop_index('ix_zl_notifications_user_unread', table_name='zl_notifications')
    op.drop_index(op.f('ix_zl_notifications_user_id'), table_name='zl_notifications')
    op.drop_index(op.f('ix_zl_notifications_is_read'), table_name='zl_notifications')
    op.drop_table('zl_notifications')
    op.drop_index(op.f('ix_zl_landing_pages_user_id'), table_name='zl_landing_pages')
    op.drop_index(op.f('ix_zl_landing_pages_slug'), table_name='zl_landing_pages')
    op.drop_table('zl_landing_pages')
    op.drop_index(op.f('ix_zl_icps_user_id'), table_name='zl_icps')
    op.drop_index('ix_zl_icps_user_active', table_name='zl_icps')
    op.drop_table('zl_icps')
    op.drop_index(op.f('ix_zl_exports_user_id'), table_name='zl_exports')
    op.drop_table('zl_exports')
    op.drop_index(op.f('ix_zl_campaigns_user_id'), table_name='zl_campaigns')
    op.drop_table('zl_campaigns')
    op.drop_index(op.f('ix_zl_users_email'), table_name='zl_users')
    op.drop_table('zl_users')
    op.drop_index(op.f('ix_zl_companies_name'), table_name='zl_companies')
    op.drop_index('ix_zl_companies_industry_city', table_name='zl_companies')
    op.drop_index(op.f('ix_zl_companies_industry'), table_name='zl_companies')
    op.drop_index(op.f('ix_zl_companies_domain'), table_name='zl_companies')
    op.drop_index('ix_zl_companies_country_industry', table_name='zl_companies')
    op.drop_index(op.f('ix_zl_companies_country'), table_name='zl_companies')
    op.drop_index(op.f('ix_zl_companies_city'), table_name='zl_companies')
    op.drop_table('zl_companies')
    # ### end Alembic commands ###
